#!/usr/bin/env python3
"""
audio_analyzer.py — 音频分析工具（Python 算法实验室）
─────────────────────────────────────────────────────────────────
目标：
  输入：song.wav / 任何音频
  输出：频谱特征 → 触觉参数建议 → JSON 预设

用法：
  python3 tools/audio_analyzer.py --input assets/test_song.wav --output presets/test.json

依赖：numpy, scipy (可选：librosa 用于高级频谱分析)
"""
import argparse
import json
import numpy as np


def extract_features(audio_path: str) -> dict:
    """简化频谱特征提取（真实版可接 librosa.mel_spectrogram）"""
    # 占位：真实实现应读取 WAV，计算 RMS、峰值频率、低频能量比例
    return {
        "bass_peak_db": -6.2,
        "beat_bpm": 128,
        "drop_time_sec": 2.4,
        "dominant_frequency_hz": 87,
        "energy_rms": 0.38,
    }


def generate_preset(features: dict, output_path: str):
    preset = {
        "name": "AutoGenerated",
        "source_audio": None,
        "features": features,
        "haptic_params": {
            "bass_boost": min(2.0, max(1.0, 1.0 + (features["energy_rms"] * 1.5))),
            "sub_bass_emphasis": 1.4,
            "beat_sync": True,
            "amplitude_scale": min(2.0, max(1.0, features["energy_rms"] * 2.5)),
        },
    }
    with open(output_path, "w") as f:
        json.dump(preset, f, indent=2)
    print(f"Preset saved: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    feat = extract_features(args.input)
    generate_preset(feat, args.output)
